syntax = "proto3";

package auth;
option go_package="github.com/GinciuuKitakaze/messenger-contracts/auth/go;auth";

import "google/protobuf/empty.proto";
import "auth/auth_model.proto";

service AuthService{
  rpc Register(RegisterRequest) returns (google.protobuf.Empty);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Refresh(RefreshRequest) returns (RefreshResponse);
  rpc Validate(ValidateRequest) returns (ValidateResponse);
  rpc Logout(RefreshRequest) returns (google.protobuf.Empty);
  rpc DeleteUserAuthData(DeleteRequest) returns (google.protobuf.Empty);
}


