// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.1
// source: users/users_service.proto

package users

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *CreateUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_users_users_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_users_users_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUser() *CreateUser {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_users_users_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_users_users_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_users_users_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_users_users_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_users_users_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_users_users_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_users_users_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_users_users_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUsersRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetUsersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_users_users_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_users_users_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserByEmailOrPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailOrPhone  string                 `protobuf:"bytes,1,opt,name=email_or_phone,json=emailOrPhone,proto3" json:"email_or_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailOrPhoneRequest) Reset() {
	*x = GetUserByEmailOrPhoneRequest{}
	mi := &file_users_users_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailOrPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailOrPhoneRequest) ProtoMessage() {}

func (x *GetUserByEmailOrPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailOrPhoneRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailOrPhoneRequest) Descriptor() ([]byte, []int) {
	return file_users_users_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserByEmailOrPhoneRequest) GetEmailOrPhone() string {
	if x != nil {
		return x.EmailOrPhone
	}
	return ""
}

type GetUserByEmailOrPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailOrPhoneResponse) Reset() {
	*x = GetUserByEmailOrPhoneResponse{}
	mi := &file_users_users_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailOrPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailOrPhoneResponse) ProtoMessage() {}

func (x *GetUserByEmailOrPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailOrPhoneResponse.ProtoReflect.Descriptor instead.
func (*GetUserByEmailOrPhoneResponse) Descriptor() ([]byte, []int) {
	return file_users_users_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserByEmailOrPhoneResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_users_users_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_users_users_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_users_users_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_users_users_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User          *UpdateUser            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_users_users_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_users_users_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetUser() *UpdateUser {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_users_users_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_users_users_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_users_users_service_proto protoreflect.FileDescriptor

const file_users_users_service_proto_rawDesc = "" +
	"\n" +
	"\x19users/users_service.proto\x12\x05users\x1a\x1cgoogle/api/annotations.proto\x1a\x17users/users_model.proto\":\n" +
	"\x11CreateUserRequest\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.users.CreateUserR\x04user\"5\n" +
	"\x12CreateUserResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"2\n" +
	"\x0fGetUserResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user\"?\n" +
	"\x0fGetUsersRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"5\n" +
	"\x10GetUsersResponse\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.users.UserR\x05users\"D\n" +
	"\x1cGetUserByEmailOrPhoneRequest\x12$\n" +
	"\x0eemail_or_phone\x18\x01 \x01(\tR\femailOrPhone\"@\n" +
	"\x1dGetUserByEmailOrPhoneResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"5\n" +
	"\x12DeleteUserResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user\"S\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x11.users.UpdateUserR\x04user\"5\n" +
	"\x12UpdateUserResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user2\xf1\x04\n" +
	"\vUserService\x12^\n" +
	"\n" +
	"CreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x04user\"\r/api/v1/users\x12Y\n" +
	"\aGetUser\x12\x15.users.GetUserRequest\x1a\x16.users.GetUserResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/users/{user_id}\x12R\n" +
	"\bGetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12\x84\x01\n" +
	"\x15GetUserByEmailOrPhone\x12#.users.GetUserByEmailOrPhoneRequest\x1a$.users.GetUserByEmailOrPhoneResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/users/by-contact\x12h\n" +
	"\n" +
	"UpdateUser\x12\x18.users.UpdateUserRequest\x1a\x19.users.UpdateUserResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x04user2\x17/api/v1/users/{user_id}\x12b\n" +
	"\n" +
	"DeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/api/v1/users/{user_id}B?Z=github.com/GinciuuKitakaze/messenger-contracts/users/go;usersb\x06proto3"

var (
	file_users_users_service_proto_rawDescOnce sync.Once
	file_users_users_service_proto_rawDescData []byte
)

func file_users_users_service_proto_rawDescGZIP() []byte {
	file_users_users_service_proto_rawDescOnce.Do(func() {
		file_users_users_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_users_service_proto_rawDesc), len(file_users_users_service_proto_rawDesc)))
	})
	return file_users_users_service_proto_rawDescData
}

var file_users_users_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_users_users_service_proto_goTypes = []any{
	(*CreateUserRequest)(nil),             // 0: users.CreateUserRequest
	(*CreateUserResponse)(nil),            // 1: users.CreateUserResponse
	(*GetUserRequest)(nil),                // 2: users.GetUserRequest
	(*GetUserResponse)(nil),               // 3: users.GetUserResponse
	(*GetUsersRequest)(nil),               // 4: users.GetUsersRequest
	(*GetUsersResponse)(nil),              // 5: users.GetUsersResponse
	(*GetUserByEmailOrPhoneRequest)(nil),  // 6: users.GetUserByEmailOrPhoneRequest
	(*GetUserByEmailOrPhoneResponse)(nil), // 7: users.GetUserByEmailOrPhoneResponse
	(*DeleteUserRequest)(nil),             // 8: users.DeleteUserRequest
	(*DeleteUserResponse)(nil),            // 9: users.DeleteUserResponse
	(*UpdateUserRequest)(nil),             // 10: users.UpdateUserRequest
	(*UpdateUserResponse)(nil),            // 11: users.UpdateUserResponse
	(*CreateUser)(nil),                    // 12: users.CreateUser
	(*User)(nil),                          // 13: users.User
	(*UpdateUser)(nil),                    // 14: users.UpdateUser
}
var file_users_users_service_proto_depIdxs = []int32{
	12, // 0: users.CreateUserRequest.user:type_name -> users.CreateUser
	13, // 1: users.CreateUserResponse.user:type_name -> users.User
	13, // 2: users.GetUserResponse.user:type_name -> users.User
	13, // 3: users.GetUsersResponse.users:type_name -> users.User
	13, // 4: users.GetUserByEmailOrPhoneResponse.user:type_name -> users.User
	13, // 5: users.DeleteUserResponse.user:type_name -> users.User
	14, // 6: users.UpdateUserRequest.user:type_name -> users.UpdateUser
	13, // 7: users.UpdateUserResponse.user:type_name -> users.User
	0,  // 8: users.UserService.CreateUser:input_type -> users.CreateUserRequest
	2,  // 9: users.UserService.GetUser:input_type -> users.GetUserRequest
	4,  // 10: users.UserService.GetUsers:input_type -> users.GetUsersRequest
	6,  // 11: users.UserService.GetUserByEmailOrPhone:input_type -> users.GetUserByEmailOrPhoneRequest
	10, // 12: users.UserService.UpdateUser:input_type -> users.UpdateUserRequest
	8,  // 13: users.UserService.DeleteUser:input_type -> users.DeleteUserRequest
	1,  // 14: users.UserService.CreateUser:output_type -> users.CreateUserResponse
	3,  // 15: users.UserService.GetUser:output_type -> users.GetUserResponse
	5,  // 16: users.UserService.GetUsers:output_type -> users.GetUsersResponse
	7,  // 17: users.UserService.GetUserByEmailOrPhone:output_type -> users.GetUserByEmailOrPhoneResponse
	11, // 18: users.UserService.UpdateUser:output_type -> users.UpdateUserResponse
	9,  // 19: users.UserService.DeleteUser:output_type -> users.DeleteUserResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_users_users_service_proto_init() }
func file_users_users_service_proto_init() {
	if File_users_users_service_proto != nil {
		return
	}
	file_users_users_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_users_service_proto_rawDesc), len(file_users_users_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_users_service_proto_goTypes,
		DependencyIndexes: file_users_users_service_proto_depIdxs,
		MessageInfos:      file_users_users_service_proto_msgTypes,
	}.Build()
	File_users_users_service_proto = out.File
	file_users_users_service_proto_goTypes = nil
	file_users_users_service_proto_depIdxs = nil
}
